config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  get "authenticate_email", to: "home#authenticate_email"

  resources :properties, only: %i[show]

  namespace :owner do 
    resources :home, only: %i[index]

    resources :properties do 
      resources :build_property

      resources :reservations, only: %i[index]
    end

    get "start_build_property", to: "home#start_build_property"
    
    resources :listings, only: %i[index]

    resources :reservations, only: %i[update]
  end

  authenticated :user, ->(user) { user.has_role? :admin} do 
    namespace :admin do 
      resources :home, only: %i[index]
      resources :properties, only: %i[index edit update]
      resources :reservations, only: %i[show]
    end
  end

  resources :reservations, only: %i[index show new create]

  get "reservation/success", to: "reservations#success"

  resources :profile, only: %i[edit update]

  resources :reviews, only: %i[create]
end

app/models/property.rb
class Property < ApplicationRecord
  extend Enumerize
  enumerize :status, in: %W[initialize add_address add_images add_headline add_description add_price pending active]

  validates :status, presence: true
  validates :street, :city, :country, presence: true, if: :pending_or_address?
  validates :headline, presence: true, if: :pending_or_headline?
  validates :description, presence: true, if: :pending_or_description?
  validates :price, presence: true, if: :pending_or_price?
  validate :filetype_is_valid, if: :pending_or_images?

  geocoded_by :address
  after_validation :geocode, if: ->{ pending? && latitude.blank? && longitude.blank? }

  has_many_attached :images, dependent: :destroy
  
  belongs_to :owner, class_name: "User"

  has_many :reservations, dependent: :destroy
  has_many :guests, through: :reservations, source: :user

  has_many :reviews, as: :reviewable, dependent: :destroy

  def address
    # [street, city, state, country].compact.join(', ')
    country
  end

  def default_image 
    images.first
  end

  def average_rating 
    reviews.average(:rating).to_f.round(1)
  end

  def pending?
    status == 'pending'
  end

  def pending_or_address? 
    status.include?('address') || pending?
  end

  def pending_or_images? 
    status.include?('images') || pending?
  end

  def pending_or_headline? 
    status.include?('headline') || pending?
  end

  def pending_or_description? 
    status.include?('description') || pending?
  end

  def pending_or_price? 
    status.include?('price') || pending?
  end

  def filetype_is_valid
    unless images.attached?
      errors.add(:images, "Images can't be blank")
      return
    end

    if images.length < 5 
      errors.add(:images, "Total images submitted must be larger than 5")
      return
    end

    images.each do |image|
      unless image.content_type.in?(%w[image/jpeg image/jpg image/png image/webp])
        errors.add(:images, "Must be JPEGm, PNG or WEBP")
      end
    end
  end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  def index 
    properties = Property.includes(:owner)
    @pending_properties = properties.where(status: "pending")
    @properties = properties.where.not(status: "pending")
  end

  def edit 
    @property = Property.includes(images_attachments: :blob).find(params[:id])
  end

  def update
    @property = Property.find(params[:id])

    if @property.update(property_params)
      #Create product on Stripe
      if @property.product_id.blank? 
        product = Stripe::Product.create({
          name: @property.headline
        })

        price = Stripe::Price.create({
          unit_amount: @property.price * 100,
          currency: 'usd',
          product: product.id,
        })
  
        @property.product_id = product.id
        @property.price_id = price.id
        @property.save
      end

      redirect_to admin_properties_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private 
  
  def property_params 
    params.require(:property).permit(:status)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show 
    @property = Property.includes(:reviews, images_attachments: :blob).find(params[:id])

    @date_ranges = []
    @property.reservations.each do |reservation|
      @date_ranges << ["#{reservation.from}", "#{reservation.to}"]
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/property/_header.slim
nav.pt-4.bg-white [data-controller="dropdown modal"] 
  .flex.items-center.justify-between.relative
    = link_to root_path do
      .text-pinkRed
        = svg_pack_tag 'airbnb_brand', alt: "Airbnb Brand"
    
    button.absolute.border-solid.border.border-gray-300.rounded-full.py-2.px-5.nav__filter.flex.items-center.gap-16
      |Start your search
      .bg-pinkRed.p-2.5.text-white.rounded-full
        = svg_pack_tag "magnitify_glass"
    
    .flex.gap-5.items-center
      - if current_user
        = link_to "Switch to hosting", owner_listings_path, class: "font-bold"     
      - else 
        = link_to "Become a Host", owner_home_index_path, class: "font-bold"

      a[href="#"]
        = svg_pack_tag "globe"
      
      .relative.header__dropdown [data-dropdown]
        button.header__dropdown-toggle.flex.items-center.gap-x-3.border.border-gray-300.rounded-full.px-3.py-2 [data-dropdown-button]
          .pointer-events-none class="space-y-0.5"
            . class="w-3.5 h-0.5 bg-gray-600"
            . class="w-3.5 h-0.5 bg-gray-600"
            . class="w-3.5 h-0.5 bg-gray-600"
          .w-8.h-8.rounded-full.pointer-events-none
            = svg_pack_tag "avatar"
        
        ul.header__dropdown-menu.absolute.w-72.right-0.top-14.py-2.px-4.bg-white.rounded-lg.z-50.text-left
          - if current_user 
            li.header__dropdown-item.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
              = link_to "Admin", admin_home_index_path, class: "font-bold" if current_user.has_role? :admin
              a.font-bold [href="#"]
                | Trips
            li.header__dropdown-item.py-4.border-b.border-gray-300
              = link_to "Switch to hosting", owner_listings_path
            li.header__dropdown-item.pt-4
              = link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } 
          - else 
            li.header__dropdown-item.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
              button.font-bold [data-action="click->modal#showModal"]
                |Sign up
              button [data-action="click->modal#showModal"]
                |Log in
            li.header__dropdown-item.pt-4
              = link_to "Host your home", owner_home_index_path

  .hidden.fixed.inset-0.bg-black.bg-opacity-60.transition-opacity.z-50 [data-modal-target="modal"]
    .flex.min-h-full.items-end.justify-center.p-4.text-center.sm:items-center.sm:p-0
      .relative.transform.overflow-hidden.rounded-lg.bg-white.text-left.pb-4.shadow-xl.transition-all.sm:my-8.sm:w-full.sm:max-w-lg
        .relative.px-4.pt-5.pb-4.sm:p-6.sm:pb-4
          button.absolute.top-4.left-4.rounded-full.p-2[data-action="click->modal#closeModal"]
            = svg_pack_tag "close_icon"
          h3#modal-title.text-lg.leading-6.text-center
            | Log in or sign up
          .
        
        h1.px-4.text-xl.mb-4.mt-7
          |Welcome to Airbnb
        
        form.px-4.flex.flex-col.gap-4.text-black [data-controller="authentication"]
          input.py-3.border.border-gray-400.rounded-lg type="email" placeholder="Email" data-authentication-target="email" class="focus:border-2 focus:border-black focus:ring-0" 

          button.inline-flex.w-full.justify-center.rounded-md.border.border-transparent.bg-pinkRed.px-4.py-3.text-base.font-bold.text-white.shadow-sm [data-action="click->authentication#submitForm"]
            | Continue
              
        .px-4.py-3.flex.flex-col.gap-4
          p.text-center.text-gray-500
            |or
          button.inline-flex.w-full.justify-between.items-center.rounded-md.border.border-gray-300.bg-white.px-4.py-3.text-base.text-black.shadow-sm.border.border-black
            = svg_pack_tag "facebook_icon"
            | Continue with Facebook
            .
          
          button.inline-flex.w-full.justify-between.items-center.rounded-md.border.border-gray-300.bg-white.px-4.py-3.text-base.text-black.shadow-sm.border.border-black
            = svg_pack_tag "google_icon"
            | Continue with Google
            .

app/views/property/show.slim
.w-screen.px-96 [data-controller="datepicker" data-datepicker-disablerange-value="#{@date_ranges}"]
  = render partial: "header"

  .mt-16
    h1.text-3xl 
      = "#{@property.headline}"
    
    .my-12.rounded-2xl.h-96.grid.grid-rows-2.grid-cols-4.overflow-hidden.gap-2
      .row-span-2.col-span-2.bg-gray-500
        = image_tag @property.default_image, class: "object-cover h-full w-full"
      .bg-gray-500 
      .bg-gray-500
      .bg-gray-500 
      .bg-gray-500

    .flex.justify-between.mb-96
      .
        h2.text-2xl.w-max.pb-4.shadow-lg.mb-4
          = "Entire villa hosted by #{@property.owner.email}"
        
        p.text-lg.text-gray-700
          = @property.description

      .sticky.border.border-gray-300.rounded-xl.right-0.top-28.p-8.flex.flex-col.gap-4 class="w-5/12" 
        h3.text-lg
          span.font-bold.text-2xl 
            |$999 
          |night
        
        = form_with url: new_reservation_path, class:"w-full flex flex-col items-center gap-4", local:true, method: :get do |f|
          = f.hidden_field :property_id, value: "#{@property.id}"

          .border.border-gray-400.rounded-lg.grid.grid-cols-2  
            .border-r.border-gray-400.flex.flex-col.p-3.items-start.rounded-l-lg class="focus:rounded-lg focus:border focus:border-black"
              h3.font-bold.text-sm
                |CHECK-IN
              = f.text_field :from, placeholder:"Add date", class:"w-full datepicker-from border-none p-0 focus:ring-0", required: true
            
            .flex.flex-col.p-3.items-start.rounded-r-lg class="focus:rounded-lg focus:border focus:border-black"
              h3.font-bold.text-sm
                |CHECKOUT
              = f.text_field :to, placeholder:"Add date", class:"w-full datepicker-to border-none p-0 focus:ring-0", required: true 
            
          - if user_signed_in?
            = f.submit "Reserve", class:"bg-pinkRed text-white px-5 py-3 rounded-lg text-lg"
          - else 
            = f.submit "Check availability", class:"bg-pinkRed text-white px-5 py-3 rounded-lg text-lg"