config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  get "authenticate_email", to: "home#authenticate_email"

  resources :properties, only: %i[show]

  namespace :owner do 
    resources :home, only: %i[index]

    resources :properties do 
      resources :build_property

      resources :reservations, only: %i[index]
    end

    get "start_build_property", to: "home#start_build_property"
    
    resources :listings, only: %i[index]

    resources :reservations, only: %i[update]
  end

  authenticated :user, ->(user) { user.has_role? :admin} do 
    namespace :admin do 
      resources :home, only: %i[index]
      resources :properties, only: %i[index edit update]
      resources :reservations, only: %i[show]
    end
  end

  resources :reservations, only: %i[index show new create]

  get "reservation/success", to: "reservations#success"

  resources :profile, only: %i[edit update]

  resources :reviews, only: %i[create]
end

app/views/shared/_authentication_modal.slim
.hidden.fixed.inset-0.bg-black.bg-opacity-60.transition-opacity.z-50 [data-modal-target="modal"]
  .flex.min-h-full.items-end.justify-center.p-4.text-center.sm:items-center.sm:p-0
    .relative.transform.overflow-hidden.rounded-lg.bg-white.text-left.pb-4.shadow-xl.transition-all.sm:my-8.sm:w-full.sm:max-w-lg
      .relative.px-4.pt-5.pb-4.sm:p-6.sm:pb-4
        button.absolute.top-4.left-4.rounded-full.p-2[data-action="click->modal#closeModal"]
          = svg_pack_tag "close_icon"
        h3#modal-title.text-lg.leading-6.text-center
          | Log in or sign up
        .
      
      h1.px-4.text-xl.mb-4.mt-7
        |Welcome to Airbnb
      
      form.px-4.flex.flex-col.gap-4.text-black [data-controller="authentication"]
        input.py-3.border.border-gray-400.rounded-lg type="email" placeholder="Email" data-authentication-target="email" class="focus:border-2 focus:border-black focus:ring-0" 

        button.inline-flex.w-full.justify-center.rounded-md.border.border-transparent.bg-pinkRed.px-4.py-3.text-base.font-bold.text-white.shadow-sm [data-action="click->authentication#submitForm"]
          | Continue
            
      .px-4.py-3.flex.flex-col.gap-4
        p.text-center.text-gray-500
          |or

        = link_to user_facebook_omniauth_authorize_path, method: :post  do
          .inline-flex.w-full.justify-between.items-center.rounded-md.border.border-gray-300.bg-white.px-4.py-3.text-base.text-black.shadow-sm.border.border-black
            = svg_pack_tag "facebook_icon"
            | Continue with Facebook
            .
        
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post do
          .inline-flex.w-full.justify-between.items-center.rounded-md.border.border-gray-300.bg-white.px-4.py-3.text-base.text-black.shadow-sm.border.border-black
            = svg_pack_tag "google_icon"
            | Continue with Google
            .

app/views/shared/_dropdown_button.slim
button.header__dropdown-toggle.flex.items-center.gap-x-3.border.border-gray-300.rounded-full.px-3.py-2 [data-dropdown-button]
  .pointer-events-none class="space-y-0.5"
    . class="w-3.5 h-0.5 bg-gray-600"
    . class="w-3.5 h-0.5 bg-gray-600"
    . class="w-3.5 h-0.5 bg-gray-600"
  .w-8.h-8.rounded-full.pointer-events-none
    = svg_pack_tag "avatar"

app/views/shared/_header_full.slim
nav.sticky.top-0.left-0.w-screen.pt-4.bg-white.lg:px-36 [data-controller="dropdown slidebar modal"]
  .flex.items-center.justify-between.relative
    = link_to root_path do
      .text-pinkRed
        = svg_pack_tag 'airbnb_brand', alt: "Airbnb Brand"

    .absolute.border-solid.border.border-gray-300.rounded-full.py-2.px-5.divide-x.divide-gray-300.nav__filter
      button.px-2
        strong
          | Anywhere
      button.px-2
        strong
          | Any week
      .px-2.inline-block
        button
          | Add guests
        button.bg-pinkRed.p-2.5.text-white.rounded-full.ml-3
          = svg_pack_tag "magnitify_glass"
    
    .flex.gap-5.items-center
      - if current_user
        = link_to "Switch to hosting", owner_listings_path, class: "font-bold"
      - else 
        = link_to "Become a Host", owner_home_index_path, class: "font-bold"
      
      - if user_signed_in? 
        = render partial: "shared/notifications"   
      
      .relative.header__dropdown [data-dropdown]
        = render partial: "shared/dropdown_button"

        ul.header__dropdown-menu.absolute.w-72.right-0.top-14.py-2.px-4.bg-white.rounded-lg.z-50.text-left
          - if current_user 
            li.header__dropdown-item.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
              = link_to "Admin", admin_home_index_path, class: "font-bold" if current_user.has_role? :admin
              = link_to "Trips", reservations_path, class: "font-bold"
            li.header__dropdown-item.py-4.border-b.border-gray-300
              = link_to "Manage listings", owner_listings_path
            li.header__dropdown-item.pt-4
              = link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } 
          - else 
            li.header__dropdown-item.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
              button.font-bold [data-action="click->modal#showModal"]
                |Sign up
              button [data-action="click->modal#showModal"]
                |Log in
            li.header__dropdown-item.pt-4
              = link_to "Host your home", owner_home_index_path
  
  .h-16.mt-16.flex.justify-between.w-full
    .container.relative.px-8
      button.absolute.border.rounded-full.border-gray-500.p-1.5.hover:p-2.top-1/4.left-0 [data-action="click->slidebar#scrollLeft" type="button"]
        = svg_pack_tag "left_arrow"
      .tags__bar.flex.gap-8.h-16.overflow-auto.whitespace-nowrap[data-slidebar-target="bar"]
        - @tags.each do |tag|
          - if tag.id == 1
            input type="radio" id="tag-#{tag.id}" name="tag" value="#{tag.id}" checked=""
          - else
            input type="radio" id="tag-#{tag.id}" name="tag" value="#{tag.id}"
          label.inline-block.flex-col.items-center.opacity-70.hover:opacity-100.cursor-pointer [for="tag-#{tag.id}" ] 
            = image_tag asset_path("tag/#{tag.icon_path}"), class: "tag__image mx-auto"
            h1.my-2.text-center.font-semibold
              = tag.name
      button.border.rounded-full.border-gray-500.p-1.5.hover:p-2.absolute.top-1/4.right-0 [data-action="click->slidebar#scrollRight" type="button"]
        = svg_pack_tag "right_arrow"
    button.py-3.px-4.my-auto.border.border-gray-300.rounded-lg.flex.items-center.gap-2
      = svg_pack_tag "filter_icon"
      |  Filters 

  = render partial: "shared/authentication_modal"

app/views/shared/_header_listing.slim
nav.sticky.top-0.left-0.w-screen.pt-4.bg-white.lg:px-36 [data-controller="dropdown"]
  .flex.items-center.justify-between.relative
    = link_to root_path do
      .text-pinkRed
        = svg_pack_tag 'airbnb_brand', alt: "Airbnb Brand"

    = link_to "Create new listing", owner_start_build_property_path, class: "text-gray-500 px-5 py-3 rounded-lg font-semibold hover:text-black"
    
    .flex.gap-5.items-center 
      - if user_signed_in? 
        = render partial: "shared/notifications" 

      .relative.header__dropdown [data-dropdown]
        = render partial: "shared/dropdown_button"
        
        ul.header__dropdown-menu.absolute.w-72.right-0.top-14.py-2.px-4.bg-white.rounded-lg.z-50.text-left
          li.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
            = link_to "Admin", admin_home_index_path, class: "font-bold" if current_user.has_role? :admin
            = link_to "Trips", reservations_path, class: "font-bold"
          li.pt-4.flex.flex-col.items-start.gap-4
            = link_to "Switch to traveling", root_path
            = link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } 

app/views/shared/_header_property.slim
nav.pt-4.bg-white [data-controller="dropdown modal"] 
  .flex.items-center.justify-between.relative
    = link_to root_path do
      .text-pinkRed
        = svg_pack_tag 'airbnb_brand', alt: "Airbnb Brand"
    
    button.absolute.border-solid.border.border-gray-300.rounded-full.py-2.px-5.nav__filter.flex.items-center.gap-16
      |Start your search
      .bg-pinkRed.p-2.5.text-white.rounded-full
        = svg_pack_tag "magnitify_glass"
    
    .flex.gap-5.items-center
      - if current_user
        = link_to "Switch to hosting", owner_listings_path, class: "font-bold"     
      - else 
        = link_to "Become a Host", owner_home_index_path, class: "font-bold"

      - if user_signed_in? 
        = render partial: "shared/notifications" 
      
      .relative.header__dropdown [data-dropdown]
        = render partial: "shared/dropdown_button"
        
        ul.header__dropdown-menu.absolute.w-72.right-0.top-14.py-2.px-4.bg-white.rounded-lg.z-50.text-left
          - if current_user 
            li.header__dropdown-item.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
              = link_to "Admin", admin_home_index_path, class: "font-bold" if current_user.has_role? :admin
              = link_to "Trips", reservations_path, class: "font-bold"
            li.header__dropdown-item.py-4.border-b.border-gray-300
              = link_to "Switch to hosting", owner_listings_path
            li.header__dropdown-item.pt-4
              = link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } 
          - else 
            li.header__dropdown-item.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
              button.font-bold [data-action="click->modal#showModal"]
                |Sign up
              button [data-action="click->modal#showModal"]
                |Log in
            li.header__dropdown-item.pt-4
              = link_to "Host your home", owner_home_index_path

  .hidden.fixed.inset-0.bg-black.bg-opacity-60.transition-opacity.z-50 [data-modal-target="modal"]
    .flex.min-h-full.items-end.justify-center.p-4.text-center.sm:items-center.sm:p-0
      .relative.transform.overflow-hidden.rounded-lg.bg-white.text-left.pb-4.shadow-xl.transition-all.sm:my-8.sm:w-full.sm:max-w-lg
        .relative.px-4.pt-5.pb-4.sm:p-6.sm:pb-4
          button.absolute.top-4.left-4.rounded-full.p-2[data-action="click->modal#closeModal"]
            = svg_pack_tag "close_icon"
          h3#modal-title.text-lg.leading-6.text-center
            | Log in or sign up
          .
        
        h1.px-4.text-xl.mb-4.mt-7
          |Welcome to Airbnb
        
        form.px-4.flex.flex-col.gap-4.text-black [data-controller="authentication"]
          input.py-3.border.border-gray-400.rounded-lg type="email" placeholder="Email" data-authentication-target="email" class="focus:border-2 focus:border-black focus:ring-0" 

          button.inline-flex.w-full.justify-center.rounded-md.border.border-transparent.bg-pinkRed.px-4.py-3.text-base.font-bold.text-white.shadow-sm [data-action="click->authentication#submitForm"]
            | Continue
              
        .px-4.py-3.flex.flex-col.gap-4
          p.text-center.text-gray-500
            |or
          button.inline-flex.w-full.justify-between.items-center.rounded-md.border.border-gray-300.bg-white.px-4.py-3.text-base.text-black.shadow-sm.border.border-black
            = svg_pack_tag "facebook_icon"
            | Continue with Facebook
            .
          
          button.inline-flex.w-full.justify-between.items-center.rounded-md.border.border-gray-300.bg-white.px-4.py-3.text-base.text-black.shadow-sm.border.border-black
            = svg_pack_tag "google_icon"
            | Continue with Google
            .

app/views/shared/_header_reservation.slim
nav.sticky.top-0.left-0.w-screen.pt-4.bg-white.lg:px-36 [data-controller="dropdown"]
  .flex.items-center.justify-between.relative
    = link_to root_path do
      .text-pinkRed
        = svg_pack_tag 'airbnb_brand', alt: "Airbnb Brand"
    
    .flex.gap-5.items-center
      - if user_signed_in? 
        = render partial: "shared/notifications"   

      .relative.header__dropdown [data-dropdown]
        = render partial: "shared/dropdown_button"
        
        ul.header__dropdown-menu.absolute.w-72.right-0.top-14.py-2.px-4.bg-white.rounded-lg.z-50.text-left
          li.w-full.flex.flex-col.items-start.gap-4.pb-4.border-b.border-gray-300
            = link_to "Admin", admin_home_index_path, class: "font-bold" if current_user.has_role? :admin
            = link_to "Trips", reservations_path, class: "font-bold"
          li.pt-4.flex.flex-col.items-start.gap-4
            = link_to "Switch to hosting", owner_listings_path 
            = link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } 

app/views/shared/_notifications.slim
.
  .h-10.w-10.relative.flex.justify-center.items-center.header__dropdown [data-dropdown]
    button.header__dropdown-toggle [data-dropdown-button]
      .pointer-events-none
        = svg_pack_tag "notification_bell", class: "w-6 h-6"

    ul.header__dropdown-menu.absolute.w-96.right-0.top-10.py-2.px-4.rounded-lg.text-left.bg-white.z-50.shadow-2xl
      h1.text-lg.font-bold.mb-2
        |Notifications
      #notification-messages-container.flex.flex-col.gap-2.divide
        - if @unread.count + @read.count == 0
          |No notifications yet.
        - else
          - @unread.each do |unread|
            li.text-md.flex.justify-between.items-center
              = link_to unread.to_notification.message, unread.to_notification.url
              .w-2.h-2.rounded-full.bg-pinkRed
          - @read.each do |read|
            li.text-md
              = link_to read.to_notification.message, read.to_notification.url

    - if user_signed_in?
      - if @unread.count > 0
        #notification-icon.absolute.h-4.w-4.bg-red-500.right-0.top-0.rounded-full.text-white.font-bold.text-sm.flex.border.border-2.border-white.p-2.border-white.items-center.justify-center.pointer-events-none [data-user-id="#{current_user.id}"]
          = @unread.count >= 9 ? "9+" : @unread.count
      - else 
        #notification-icon.absolute.h-4.w-4.bg-red-500.right-0.top-0.rounded-full.text-white.font-bold.text-sm.hidden.border.border-2.border-white.p-2.border-white.items-center.justify-center.pointer-events-none [data-user-id="#{current_user.id}"]
          |0
    
    

app/views/shared/_progress_step_bar.slim
.w-full.py-6
  .flex
    . class="w-1/4"
      .relative.mb-2
        .bg-pinkRed.text-white.w-10.h-10.mx-auto.rounded-full.text-lg.flex.items-center
          span.text-center.w-full
            = svg_pack_tag "database_icon", class: "w-full fill-white"
      .text-xs.text-center.md:text-base
        | Reservation created
    
    . class="w-1/4"
      .relative.mb-2
        .absolute.flex.align-center.items-center.align-middle.content-center[style="width: calc(100% - 2.5rem - 1rem); top: 50%; transform: translate(-50%, -50%)"]
          .w-full.bg-gray-200.rounded.items-center.align-middle.align-center.flex-1
            - if status_step < 1
              .w-0.bg-pinkRed.py-1.rounded[style="width: 0%;"]
            - else 
              .w-0.bg-pinkRed.py-1.rounded[style="width: 100%;"]

        .bg-pinkRed.text-white.w-10.h-10.mx-auto.rounded-full.text-lg.flex.items-center
          span.text-center.w-full
            = svg_pack_tag "setting_icon", class: "w-full fill-white"
      .text-xs.text-center.md:text-base
        | Processing
      
    . class="w-1/4"
      .relative.mb-2
        .absolute.flex.align-center.items-center.align-middle.content-center[style="width: calc(100% - 2.5rem - 1rem); top: 50%; transform: translate(-50%, -50%)"]
          .w-full.bg-gray-200.rounded.items-center.align-middle.align-center.flex-1
            - if status_step < 2
              .w-0.bg-pinkRed.py-1.rounded[style="width: 0%;"]
            - else 
              .w-0.bg-pinkRed.py-1.rounded[style="width: 100%;"]
        
        - if status_step < 2 
          .bg-white.text-black.w-10.h-10.mx-auto.border-2.border-gray-200.rounded-full.text-lg.flex.items-center
            span.text-center.w-full.flex.justify-center.items-center
              = svg_pack_tag "success_icon"
        - else
          .bg-pinkRed.text-white.w-10.h-10.mx-auto.border-2.border-gray-200.rounded-full.text-lg.flex.items-center.justify-center
            span.text-center.w-full
              = svg_pack_tag "success_icon", class: "w-full fill-white"

      .text-xs.text-center.md:text-base
        | Success
        
    . class="w-1/4"
      .relative.mb-2
        .absolute.flex.align-center.items-center.align-middle.content-center[style="width: calc(100% - 2.5rem - 1rem); top: 50%; transform: translate(-50%, -50%)"]
          .w-full.bg-gray-200.rounded.items-center.align-middle.align-center.flex-1
            - if status_step < 3
              .w-0.bg-pinkRed.py-1.rounded[style="width: 0%;"]
            - else 
              .w-0.bg-pinkRed.py-1.rounded[style="width: 100%;"]

        - if status_step < 3    
          .bg-white.text-black.w-10.h-10.mx-auto.border-2.border-gray-200.rounded-full.text-lg.flex.items-center.justify-center
            span.text-center.w-full.flex.justify-center.items.center
              = svg_pack_tag "star_border_icon"
        - else 
          .bg-pinkRed.text-white.w-10.h-10.mx-auto.border-2.border-gray-200.rounded-full.text-lg.flex.items-center.justify-center
            span.text-center.w-full.flex.justify-center.items-center
              = svg_pack_tag "star_border_icon"
      .text-xs.text-center.md:text-base
        | Completed
    

app/views/shared/_properties_list.slim
.col-span-full.text-2xl 
  = table_name
.text-gray-500.font-bold.text-lg
  |ID
.text-gray-500.font-bold.text-lg.col-start-2.col-span-2
  |Owner
.text-gray-500.font-bold.text-lg.col-start-4.col-span-4
  |Address 
.text-gray-500.font-bold.text-lg  
  |Status 
.text-gray-500.font-bold.text-lg  
  |Num.Reservations

- properties.each do |property|    
  .
    = link_to "#{property.id}", property_path(property), class: "hover:text-blue-600", title: "Click here for property page"

  .col-start-2.col-span-2
    = property.owner.email

  .col-start-4.col-span-4
    = link_to "#{[property.street, property.city, property.state, property.country].compact.join(', ')}", owner_property_build_property_index_path(property_id: property.id), class: "hover:text-blue-600", title:"Click here to update property's address"

  . 
    = link_to "#{property.status == "" ? "Initializing" : property.status.capitalize}", edit_admin_property_path(property), class: "hover:text-blue-600", title: "Update property's status"
  .text-center 
    - if disable_reservations 
      |Disabled
    - else
     = link_to "#{property.reservations.count}", admin_reservation_path(property), class: "hover:text-blue-600", title: "Property's reservations"

app/views/shared/_reservations_list.slim
.p-4.flex.flex-col class="w-9/12"
  .grid.grid-cols-8.my-4.gap-y-4
    .col-span-full.text-2xl 
      |RESERVATIONS
    .text-gray-500.font-bold.text-lg
      |ID
    .text-gray-500.font-bold.text-lg.col-span-2
      |Guest
    .text-gray-500.font-bold.text-lg.col-span-2
      |Address 
    .text-gray-500.font-bold.text-lg.col-span-2 
      |Duration
    .text-gray-500.font-bold.text-lg 
      |Status

    - reservations.each do |reservation|    
      .
        = reservation.id
      .col-span-2
        = reservation.user.email
      .col-span-2
        = reservation.property.address
      .col-span-2  
        = "#{reservation.from} - #{reservation.to}"
      .
        = "#{reservation.status.capitalize}"

app/views/shared/_return.slim
= link_to root_path, class: "fixed top-8 right-8" do
  .text-pinkRed
    = svg_pack_tag 'airbnb_brand', alt: "Airbnb Brand"

app/views/shared/_sidebar.slim
.nav.h-screen.bg-pinkRed.text-white.p-4.flex.flex-col.gap-4
    .text-xl
      |ADMIN DASHBOARD

    ul.flex.flex-col.gap-3.divide-y.divide-white.divide-solid
      li.text-lg
        = link_to "Users", admin_home_index_path 
      li.text-lg
        = link_to "Properties", admin_properties_path