config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  get "authenticate_email", to: "home#authenticate_email"

  resources :properties, only: %i[show]

  namespace :owner do 
    resources :home, only: %i[index]

    resources :properties do 
      resources :build_property

      resources :reservations, only: %i[index]
    end

    get "start_build_property", to: "home#start_build_property"
    
    resources :listings, only: %i[index]

    resources :reservations, only: %i[update]
  end

  authenticated :user, ->(user) { user.has_role? :admin} do 
    namespace :admin do 
      resources :home, only: %i[index]
      resources :properties, only: %i[index edit update]
      resources :reservations, only: %i[show]
    end
  end

  resources :reservations, only: %i[index show new create]

  get "reservation/success", to: "reservations#success"

  resources :profile, only: %i[edit update]

  resources :reviews, only: %i[create]
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  def index 
    @users = User.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
    @tags = Tag.all
    @properties = Property.where(status: "active")
  end

  def authenticate_email
    user = User.find_by!(email: params[:email])

    respond_to do |format| 
      format.json do 
        render json: user.to_json, status: :ok
      end
    end

  rescue ActiveRecord::RecordNotFound => e
    respond_to do |format| 
      format.json do 
        render json: { error: e.message }.to_json, status: 204
      end
    end
  end
end

app/controllers/owner/home_controller.rb
class Owner::HomeController < ApplicationController
  before_action :authenticate_user!, only: [:start_build_property]
  
  def index 
  end

  def start_build_property 
    if current_user.profile.identification_image.attached?
      @property = current_user.properties.build(status: :initialize)
      @property.save
      redirect_to owner_property_build_property_index_path(property_id: @property.id)
    else
      redirect_to edit_profile_path(current_user.profile)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/_sidebar.slim
.nav.h-screen.bg-pinkRed.text-white.p-4.flex.flex-col.gap-4
    .text-xl
      |ADMIN DASHBOARD

    ul.flex.flex-col.gap-3.divide-y.divide-white.divide-solid
      li.text-lg
        = link_to "Users", admin_home_index_path 
      li.text-lg
        = link_to "Properties", admin_show_properties_path
      li.text-lg 
        = link_to "Reservations",admin_show_reservations_path

app/views/admin/home/index.slim
= render partial: "shared/return"

.flex 
  = render partial: "shared/sidebar"
  .p-4.flex.flex-col class="w-10/12"
    .text-2xl 
      |USERS 

    table.mt-4 class="w-1/2 table-auto"
      thead
        tr.text-left.text-gray-500.font-bold 
          th 
            |ID
          th 
            |Email
          th 
            |Profile link
      tbody
        - @users.each do |user|    
          tr
            td 
              = "#{user.id}"
            td
              = "#{user.email}"
            td 
              | Click

app/views/admin/home/show_properties.slim
= render partial: "return"

.flex 
  = render partial: "sidebar"
  .p-4.flex.flex-col class="w-10/12"
    .text-2xl 
      |PROPERTIES

    table.mt-4 class="w-10/12 table-auto"
      thead
        tr.text-left.text-gray-500.font-bold 
          th 
            |ID
          th 
            |Owner
          th 
            |Address 
          th 
            |Status 

      tbody
        - @properties.each do |property|    
          tr
            td 
              = property.id
            td
              = property.owner.email
            td 
              = [property.street, property.city, property.state, property.country].compact.join(', ')
            td 
              = property.status == "" ? "Initializing" : property.status.capitalize

app/views/admin/home/show_reservations.slim
= render partial: "return"

.flex 
  = render partial: "sidebar"
  .p-4.flex.flex-col class="w-10/12"
    .text-2xl 
      |RESERVATIONS

    table.mt-4 class="w-10/12 table-auto"
      thead
        tr.text-left.text-gray-500.font-bold 
          th 
            |ID
          th 
            |User
          th 
            |Property 
          th 
            |Duration
          th 
            |Status (add later)

      tbody
        - @reservations.each do |reservation|    
          tr
            td 
              = reservation.id
            td
              = reservation.user.email
            td 
              = reservation.property.address
            td 
              = "#{reservation.from} - #{reservation.to}"