config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  get "authenticate_email", to: "home#authenticate_email"

  resources :properties, only: %i[show]

  namespace :owner do 
    resources :home, only: %i[index]

    resources :properties do 
      resources :build_property

      resources :reservations, only: %i[index]
    end

    get "start_build_property", to: "home#start_build_property"
    
    resources :listings, only: %i[index]

    resources :reservations, only: %i[update]
  end

  authenticated :user, ->(user) { user.has_role? :admin} do 
    namespace :admin do 
      resources :home, only: %i[index]
      resources :properties, only: %i[index edit update]
      resources :reservations, only: %i[show]
    end
  end

  resources :reservations, only: %i[index show new create]

  get "reservation/success", to: "reservations#success"

  resources :profile, only: %i[edit update]

  resources :reviews, only: %i[create]
end

app/models/property.rb
class Property < ApplicationRecord
  extend Enumerize
  enumerize :status, in: %W[initialize add_address add_images add_headline add_description add_price pending active]

  validates :status, presence: true
  validates :street, :city, :country, presence: true, if: :pending_or_address?
  validates :headline, presence: true, if: :pending_or_headline?
  validates :description, presence: true, if: :pending_or_description?
  validates :price, presence: true, if: :pending_or_price?
  validate :filetype_is_valid, if: :pending_or_images?

  geocoded_by :address
  after_validation :geocode, if: ->{ pending? && latitude.blank? && longitude.blank? }

  has_many_attached :images, dependent: :destroy
  
  belongs_to :owner, class_name: "User"

  has_many :reservations, dependent: :destroy
  has_many :guests, through: :reservations, source: :user

  has_many :reviews, as: :reviewable, dependent: :destroy

  def address
    # [street, city, state, country].compact.join(', ')
    country
  end

  def default_image 
    images.first
  end

  def average_rating 
    reviews.average(:rating).to_f.round(1)
  end

  def pending?
    status == 'pending'
  end

  def pending_or_address? 
    status.include?('address') || pending?
  end

  def pending_or_images? 
    status.include?('images') || pending?
  end

  def pending_or_headline? 
    status.include?('headline') || pending?
  end

  def pending_or_description? 
    status.include?('description') || pending?
  end

  def pending_or_price? 
    status.include?('price') || pending?
  end

  def filetype_is_valid
    unless images.attached?
      errors.add(:images, "Images can't be blank")
      return
    end

    if images.length < 5 
      errors.add(:images, "Total images submitted must be larger than 5")
      return
    end

    images.each do |image|
      unless image.content_type.in?(%w[image/jpeg image/jpg image/png image/webp])
        errors.add(:images, "Must be JPEGm, PNG or WEBP")
      end
    end
  end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  def index 
    properties = Property.includes(:owner)
    @pending_properties = properties.where(status: "pending")
    @properties = properties.where.not(status: "pending")
  end

  def edit 
    @property = Property.includes(images_attachments: :blob).find(params[:id])
  end

  def update
    @property = Property.find(params[:id])

    if @property.update(property_params)
      #Create product on Stripe
      if @property.product_id.blank? 
        product = Stripe::Product.create({
          name: @property.headline
        })

        price = Stripe::Price.create({
          unit_amount: @property.price * 100,
          currency: 'usd',
          product: product.id,
        })
  
        @property.product_id = product.id
        @property.price_id = price.id
        @property.save
      end

      redirect_to admin_properties_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private 
  
  def property_params 
    params.require(:property).permit(:status)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show 
    @property = Property.includes(:reviews, images_attachments: :blob).find(params[:id])

    @date_ranges = []
    @property.reservations.each do |reservation|
      @date_ranges << ["#{reservation.from}", "#{reservation.to}"]
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/admin/properties/edit.slim
= render partial: "shared/return"

.flex
  = render partial: "shared/sidebar"
  
  .p-6.flex.flex-col.gap-8 class="w-10/12"
    .text-2xl
      |UPDATE PROPERTY STATUS

    .rounded-2xl.h-96.grid.grid-rows-2.grid-cols-4.overflow-hidden.gap-2 class="w-2/3"
      .row-span-2.col-span-2.bg-gray-500
        = image_tag @property.default_image, class: "object-cover h-full w-full"
      - @property.images[1..4].each do |image|
        .bg-gray-500 
          = image_tag image, class: "object-cover h-full w-full"

    ul.text-lg.flex.flex-col.gap-2 class="w-2/3"
      li 
        = "Property's ID: #{@property.id}"
      li 
        = "Owner: #{@property.owner.email}"
      li 
        = "Address: #{[@property.street, @property.city, @property.state, @property.country].compact.join(', ')}"
      li.flex.items-center.gap-2
        p
          |Current status: 
        = form_with model: @property, url: admin_property_path, method: :patch, class: "flex gap-2" do |f|
          = f.select :status, options_for_select([["Pending", "pending"], ["Active", "active"]], selected: @property.status, disabled: @property.status), {}, class: "w-32 text-lg rounded-lg focus:border-none focus:ring-0 focus:outline focus:outline-2 focus:outline-black p-2", autocomplete: "off"
          = f.submit "Change status", class: "w-40 bg-pinkRed rounded-lg p-3 text-white text-lg"
    
    

app/views/admin/properties/index.slim
= render partial: "shared/return"

.flex 
  = render partial: "shared/sidebar"
  .p-4.flex.flex-col class="w-9/12"
    .grid.grid-cols-9.my-4.gap-y-4
      = render partial: "shared/properties_list", locals: {table_name: "PENDING PROPERTIES", properties: @pending_properties, disable_reservations: true}      
      = render partial: "shared/properties_list", locals: {table_name: "PROPERTIES", properties: @properties, disable_reservations: false}